data/test_transforms.py, data/transforms.py
Fixed a subtle bug in the masking code. 
The old code applies the sub-sampling mask to k-space by multiplying k-space data with the mask. The resulting masked k-space can have 0 or -0 in the unobserved k-space points, which leaks information about the sign of the unobserved k-space  points.
With this change, the unobserved k-space points always take on the value of 0 after applying the mask.
=> Fixed negative zero bug in mask

README.md
The current link to the submission page in the Readme is relative and you therefore end up on this page: https://github.com/facebookresearch/fastMRI/blob/master/fastmri.org/submit .
(which is obviously a 404).
Adding http in front of the url allows to make the link absolute.
=> Relative link to submission page corrected

README.md
Replaced with correct link to the ```train_unet.py``` tutorial script in ```README.md```.
=> [Fix broken link to UNET tutorial]

README.md, common/args.py, common/evaluate.py, common/subsample.py, common/test_subsample.py, data/README.md, data/test_transforms.py, fastMRI_tutorial.ipynb, models/cs/README.md, models/cs/run_bart_test.py, models/cs/run_bart_val.py, models/unet/README.md, models/unet/run_unet.py, models/unet/train_unet.py, models/unet/unet_model.py, models/zero_filled/run_zero_filled.py
This PR adds support for the upcoming brain dataset. Specifically it adds:
- Handling of arbitrary sized kspace and target images (in dataloaders and UNet model)
- Adding equispaced masks, which can be chosen with a command line argument
- Hard coding best regularization weights for each brain sequence type when using TV.
=> Brain Dataset Support

experimental/unet/unet_module.py, experimental/varnet/varnet_module.py, experimental/zero_filled/run_zero_filled.py, fastmri/data/mri_data.py
This PR updates cropping routine for the U-Net and VarNet. Previously, both of these training modules had a `resolution` parameter that specified the cropping for the final image. This behavior has been removed and replaced with new logic that reads the final cropped image size from the `ismrmrd` header. This is particularly applicable to the brain data, where a single `resolution` parameter does not work for most cases.
The PR also includes minor updates to docstrings.
=> Updates for cropping for U-Net and VarNet

fastmri/mri_module.py
There was a bug in validation_epoch_end in the `MriModule` where the slices were concatenated along a spatial dimension instead of a new slice dimension. `evaluate.ssim` operated on these single concatenated slices instead of volumes and therefore there was no averaging along the slice dimension.
=> Fixed SSIM evaluation bug

experimental/unet/train_unet_demo.py, experimental/varnet/train_varnet_demo.py, fastmri/mri_module.py
The random seed of `SliceDataset` has not been explicitly set on the experiment level. Different processes during ddp training had different random seed. This led to different parts of the training data selected by different workers if `args.sub_sample < 1`.  Now the default behavior in unet/varnet experiments is `deterministic` and the same portion of data is selected by processes.
=> Fixed experiment random seed for proper ddp subsampling

fastmri/data/subsample.py
This adds a comment to the documentation of the equispaced mask function that it doesn't not generate perfectly equispaced masks as mentioned in Issue #54.
=> Adding an equispaced mask comment

experimental/unet/train_unet_demo.py, experimental/varnet/train_varnet_demo.py, fastmri/__init__.py, fastmri/evaluate.py, fastmri/pl_modules/__init__.py, fastmri/pl_modules/configure_checkpoint.py, fastmri/pl_modules/mri_module.py, fastmri/pl_modules/unet_module.py, fastmri/pl_modules/varnet_module.py, requirements.txt, setup.py, tests/conftest.py, tests/test_data.py, tests/test_math.py, tests/test_models.py, tests/test_modules.py, tests/test_transforms.py
This updates the logging components for PyTorch Lightning 1.0.0 - part of the Issue #84 roadmap.
This is a big update. Most importantly it does:
- Updates return values from `validation_step` so that only metrics are stored long-term. This should reduce memory consumption quite a bit during the validation loop. It also minimizes device management which should make NCCL a little more robust.
- Alters image logging in a way that is flexible for multiple image shapes. Also adds a new parameter for how many images to log.
- Adds a `max_value` to U-Net and VarNet transforms. This allows the computation of SSIM in `validation_step_end` without knowledge of all other slices in the volume.
- Homogenizes handling of experimental directories via `default_root_dir` in the main client script. 
- …
=> Update logging for PyTorch Lightning 1.0.0

.circleci/config.yml, experimental/zero_filled/run_zero_filled.py, fastmri/data/mri_data.py, requirements.txt, setup.py
This PR removes the ISMRMRD dependency. ISMRMRD depends on `pyxb`, which is at [end-of-life](https://github.com/pabigot/pyxb/issues/100). Removing this dependency should help stabilize the fastMRI repository for the long run.
There is only one place we need the `ismrmrd` Python package: to parse the xml header in the `.hf` files. This update replaces `ismrmrd` with `ElementTree`, which is part of the Python standard library. I've re-run all integration tests with this update and checked that the generated `dataset_cache.pkl` files have identical values vs. the old version.
=> Remove ismrmrd dependency

.circleci/config.yml, .gitignore, fastmri/math.py, requirements.txt
This future-proofs us (Issue #84) for PyTorch 1.7 FFT functions. A version check is applied to make sure the import is handled properly.
=> Add ffts for PyTorch 1.7

fastmri/data/mri_data.py, fastmri/pl_modules/data_module.py, fastmri/pl_modules/unet_module.py, tests/conftest.py, tests/create_temp_data.py, tests/test_data.py, tests/test_integrations.py, tests/test_modules.py
This adds dataset mocking so that we can keep track of our data loaders and PyTorch Lightning modules in CircleCI. This is part of our ongoing initiative to get the repo to longterm stability (Issue #84) It creates a little mock dataset and reads from it.
Dealing with the ISMRMRD header is a little more funky so I decided to just `monkeypatch` it.
The dataset tests evaluate the three main data set functions: `__init__`, `__len__`, and `__getitem__`. They don't validate the content of the mocked data.
The module tests use the data splits to run one step each of `train`, `val`, and `test`.
=> Add dataset mocking

fastmri/__init__.py, fastmri/fftc.py, fastmri/math.py, fastmri/models/unet.py, fastmri/models/varnet.py, tests/test_math.py, tests/test_models.py, tests/test_modules.py
This PR makes the U-Net and VarNet models scriptable, an item in Issue #84.
`torch.jit.script` really punishes use of high-level Python functions. To get this to work I had to modify a number of areas in the code base so that the compiler would work - reasons for modifications include type recognition, unsupported functions, use of globals, etc.
For the future I've also added a `torch.jit.script` test to make sure that any changes we make won't break this new feature.
=> Make models scriptable

fastmri/data/subsample.py
Change is to use RandomState(). Without it, there's the error received that a module object can't be pickled. The error is in reproducible in Windows 10 and OS X Catalina.
=> Fix to the issues of running unit tests and 

fastmri_examples/unet/train_unet_demo.py, fastmri_examples/varnet/train_varnet_demo.py
This fixes the monitor for `ModelCheckpoint` in the demo scripts as identified in Issue #108. Previously it was set to `val_loss`, which has been renamed due to a [Pytorch Lightning issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/4553).
I've tested this update past one epoch and it logs checkpoints as expected.
=> Fix monitor

dev-requirements.txt, requirements.txt
Fixes `mypy` failures in PR #119 by fixing versions in `requirements.txt` and `dev-requirements.txt`. We should have fixed these to begin with to prevent test flakiness.
=> Fix all versions

fastmri/data/volume_sampler.py
Currently VolumeSampler crashes if the number of unique slices assigned to a certain GPU is less than half of `num_samples`. This can happen if the number of slices across volumes in a dataset varies a lot. To fix this issue we can repeat all assigned indices to close the gap before exactly matching `num_samples`.
=> VolumeSampler fix

fastmri/evaluate.py, fastmri/pl_modules/mri_module.py
`evaluate.ssim` receives a 2D array when a 3D array is expected with a slice dimension first. This results in wrong validation SSIM, which is fixed by adding a singleton dimension to the recons and targets.
Maybe a dimension check in `evaluate.ssim` would help avoiding this bug later?
=> validation ssim fix

fastmri/evaluate.py, fastmri/pl_modules/mri_module.py
This fixes metric aggregation for NMSE and PSNR in the validation loop of the Lightning modules, which likely caused Issue #129. Previously, NMSE was being normalized with the slice norm and PSNR was using the maximum value of the slice. Both of these should have been using volume metrics to match the methodology in the fastMRI paper. This PR fixes the volume metrics.
**Previous U-Net Knee Single-Coil**
NMSE: 0.04213
PSNR: 27.02
**This PR (epoch 43)**
NMSE: 0.0323
PSNR: 32.34
=> Fix NMSE and PSNR aggregation in validation loop

fastmri/pl_modules/mri_module.py
The present code to log images during training assumes that there is a single Lightning logger in place, and that it is a `TensorboardLogger`. This PR changes that to allow for multiple loggers, and logs images only to those that are Tensorboard `SummaryWriters`.
=> Make image logging more flexible

fastmri_examples/cs/README.md, fastmri_examples/cs/run_bart.py, fastmri_examples/zero_filled/README.md, fastmri_examples/zero_filled/run_zero_filled.py
Fix output path mentioned in the [CS example README](https://github.com/facebookresearch/fastMRI/tree/master/fastmri_examples/cs) to match the one required in [run_bart.py](https://github.com/facebookresearch/fastMRI/blob/master/fastmri_examples/cs/run_bart.py).
Changed from `output_path` to `out_path` and detailed a bit more the `TOOLBOX_PATH` environmental 
variable setting.
Both the CS and Zero Filled experiments use `out_path` whilst UNet and VarNet use `output_path`. Maybe we could standardize into one of them?
=> [WIP] Fix out_path argument and describe TOOLPATH pointing location

.github/workflows/publish-package.yml, .gitignore, README.md, fastmri/__init__.py, setup.py
Adds a version and metadata to `setup.py` to make distributing on PyPI possible. Also adds a GitHub workflow that will automatically take care of this for us when we create a release.
=> Update package for PyPI distribution

README.md, fastmri/__init__.py, setup.py
This PR fixes the `find_packages` command to correctly exclude the `fastmri_examples` directory. It also includes modifications to the README so that links are correctly resolved on PyPI.
=> Fix excludes in find_packages

requirements.txt, setup.py
Fixes an issue that can occur with PyPI installation where `packaging` is not already installed.
=> Add packaging to setup requirements

fastmri/models/varnet.py
`VarNetBock` should be `VarNetBlock`, as seen in
https://github.com/facebookresearch/fastMRI/blob/a588fb1b7980175e6fe6b17497148e02daf31c12/fastmri/models/varnet.py#L243
=> Fix typo in varnet.py

fastmri/pl_modules/data_module.py
This would allow the use of the [`predict`](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#predict) method from the ptl trainer in order to evaluate the data volume-wise.
I think it would also not cause any issue because the validation data does not need to be shuffled unlike the training data.
I didn't open an issue because this is such a small PR, but glad to if needed.
=> No Shuffle for samplers and loaders in data module for test and validation

fastmri/data/transforms.py, fastmri/models/varnet.py, tests/test_models.py
This adds batching capability for the VarNet mask. There is a bit of a question of how to handle cases where a sample is selected right next to the densely sampled region. To give an example, you may have R=4 and a densely-sampled region of 8. It's possible for one line of your R=4 to be next to the R=8 group. In that case, this code will select 9 lines for a batch size of 1. Using a batch size of greater than 1 introduces some randomness. The code is conservative and will generally pick 8 lines in that case.
One way to solve this might be to only allow even numbers of central k-space lines, which might give a bit more simplicity for this phenomenon. The effects are probably measurable, but small, considering this is just input to a neural network.
Note: we still expect this to only work …
=> Add batching capability for VarNet mask

fastmri/pl_modules/data_module.py
`num_workers` was a `float` argparse arg, which threw errors when setting it through command line.
=> num_workers in data_module is now an int instead of float

fastmri/models/varnet.py, tests/test_models.py
This PR adds a new feature to the VarNet to allow using the full k-space for sensitivity estimation. The option is enabled by turning off the new `mask_center` parameter in the `VarNet`.
While writing this I also realized there were some unused variables in the VarNet tests. I've enabled those variables and removed those which didn't make sense.
=> Update sensitivity model to allow full k-space for sensitivity estimation

dev-requirements.txt, fastmri/__init__.py, fastmri/data/subsample.py, fastmri/data/transforms.py, fastmri/evaluate.py, fastmri/fftc.py, fastmri/math.py, requirements.txt, setup.py, tests/test_transforms.py
This splits off the test requirements update from #167 to reduce the number of files modified in that diff. It supersedes #166.
- There are several changes due to the `mypy` update, which caught a few new issues with type annotations. In general strict type adherence is best, so we've created some new variables for things such as `Tensor` conversion (specifically, in `UnetDataTransform` and `VarNetDataTransform`).
- Since we now have a standardized requirements framework and versioning we can drop support for pre-1.7.0 PyTorch FFTs and drop `packaging` as a requirement.
=> Update requirements for test and install

fastmri/__init__.py, fastmri/data/subsample.py, fastmri/data/transforms.py, fastmri/models/varnet.py, fastmri/pl_modules/unet_module.py, fastmri/pl_modules/varnet_module.py, fastmri_examples/unet/train_unet_demo.py, fastmri_examples/varnet/train_varnet_demo.py, tests/test_models.py, tests/test_transforms.py
This update implements a major overhaul of the masking API for the repository. The primary reason for doing this was to implement the [magic mask](https://arxiv.org/abs/1912.01101) in the core repository. Already, we had repeated code in several sections, and with the new mask this would be duplicated again and be bad for maintenance. With the new code structure, everything is subclassed from a base mask function in a modular way, so for the future we'll hopefully only need to change the base class to make updates.
We also implemented a few other things that came from the internal fastMRI repository (most of which has already been exposed via `banding_removal`). These include returning the number of low frequency lines (for sensitivity map estimation) and segmenting out the equispaced …
=> Update for subsample masking API

fastmri/data/subsample.py, tests/test_transforms.py
Patches an error - the `integers` function is not available to `np.random.RandomState`.
This PR also added a test for all mask types to hopefully automatically detect this issue in the future.
=> Fix random integers

fastmri/data/subsample.py, tests/test_transforms.py
This PR allows the user to use different-length center-fractions and accelerations. It also allows mixing between center fractions and accelerations.
**Old Code**
For example, if the user inputs `[0.08, 0.04]` for `center_fractions` and `[4, 8]` for accelerations, under the previous code, `0.08` would always be selected with `4` and `0.04` would always be selected with `8`.
**New Code**
We have a parameter, `sync_center_fractions_accelerations` in `MaskFunc`. If `sync_center_fractions_accelerations` is `False`, then now `0.08` can be selected with `8` and `0.04` can be selected with `4`.
=> Allow different-length center fractions/accelerations

fastmri/models/varnet.py, tests/test_models.py, tests/test_transforms.py
`num_sense_lines` is no longer used, so let's get rid of it.
This PR also introduces some new tests to assert that the VarNet masking operations select the center lines correctly, as well as making sure that masks correctly sample the center.
=> Add masking tests, remove unnecessary num_sens_lines

.github/workflows/build-and-test.yml
This updates CI to avoid duplicate triggers on `push` and `pull_request`. For the old `push` case we now ask the user to manually trigger the tests with `workflow_dispatch` using the GitHub website UI. All pull requests should still be tested.
=> Update CI triggers

README.md
Adds a warning to the README about the memory leak discovered in Issue #215. The current way to work around the memory leak is to use the `conda` version of `h5py` 3.6.0 or to use a `pip` version of `h5py` 3.3 or earlier.
=> Add warning about pip h5py

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/config.yml
Implements templates for opening new issues.
Guides users to Discussions if they're not requesting a feature or documenting a bug.
=> Implement issue templates

fastMRI_tutorial.ipynb
Some changes to `apply_mask` make it return 3 parameters, but the old tutorial only has two.
=> Add a dummy to the return of the apply_mask function to prevent errors

fastmri/data/mri_data.py
Fixes issue #275 
If no annotation_version is provided, the latest version of the annotation data will be used.
Also, some rows in the [annotation data](https://raw.githubusercontent.com/microsoft/fastmri-plus/main/Annotations/knee.csv) have study_level == 'Yes' and do not provide x- and y-values, which lead to an error previously. This is solved by setting the x- and y-value to -1 in this case, similar to the case when no annotation is provided for the MRI-volume.
=> Fix for AnnotatedSliceDataset

fastmri/models/varnet.py
in pytorch 2.0, the output of pad on line 199 is being interpreted as a float (even with the floor div). This raises an error when using the pad value for index computation. As a precaution, we cast to long which can be interpreted as an int
=> typecast indices to long to avoid being interpreted as float

fastmri/data/mri_data.py
Fixes #309 by using out-of-place updates for `raw_samples` in `AnnotatedSliceDataset`.
=> Fix annotation extraction

.github/workflows/build-and-test.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command
