.gitignore, common/args.py, data/mri_data.py, data/transforms.py, models/mri_model.py, models/unet/train_unet.py, models/varnet/README.md, models/varnet/varnet.py, requirements.txt
Implementation for "End-to-End Variational Networks for Accelerated MRI Reconstruction" method.
=> End-to-End Variational Network

data/mri_data.py, models/unet/train_unet.py, models/varnet/varnet.py
Edited the files `data/mri_data.py` and `models/varnet/varnet.py` to make the varnet reconstruction code work in the "test" mode.
=> Committed changes for the varnet related to the "test" mode

common/evaluate.py, common/utils.py, data/volume_sampler.py, models/mri_model.py, models/unet/train_unet.py, models/varnet/varnet.py
Here are some left over changes from my working directory that i've been meaning to push upstream.
- Fixes distributed training by adding a VolumeSampler class
- Adds acceleration filter for evaluation script
- Fix bug with some resolutions
- Several style changes
=> Fix distributed training

banding_removal/fastmri/transform_mixin.py, banding_removal/fastmri/transforms/orientation.py, banding_removal/scripts/pretrain.py, banding_removal/scripts/train.py
The current banding removal code is actually missing a file, this should make it runnable.
=> Fixes to the orientation adversary

fastmri/data/subsample.py, tests/test_transforms.py
This PR introduces a context manager to `MaskFunc` so that it doesn't change the Numpy random state in other functions.
=> Mask func random state context management

experimental/cs/README.md, experimental/cs/cs_config.yaml, experimental/cs/run_bart.py, fastmri/__init__.py, fastmri/math.py
This PR adds compressed sensing (via BART) with brain cropping to the `experimental` folder. So far I've verified that it runs for both `val` and `test` splits. I've yet to check SSIM values against those posted on the leaderboard.
This continues progress on the roadmap laid out in Issue #50.
=> Added BART with brain cropping

experimental/unet/README.md, experimental/varnet/README.md
Add a couple of comments explaining the leaderboard submission scripts in `experimental`.
=> Updates explaining leaderboard submission scripts

fastmri/data/mri_data.py
Allows the user to filter the dataset so that it only returns slices of the desired number of columns.
=> Added option to filter slices by number of columns

tests/conftest.py
Fixed the data set lengths in `conftest.py`.
=> Fixed dataset lengths

README.md, experimental/brain_challenge_inference/README.md, experimental/brain_challenge_inference/run_brain_challenge_inference.py, experimental/brain_challenge_inference/run_brain_challenge_transfer_inference.py
This PR includes scripts for running inference on the 2020 fastMRI Reconstruction Challenge data.
=> 2020 fastMRI challenge launch

.circleci/config.yml, dev-requirements.txt, fastmri/coil_combine.py, fastmri/data/mri_data.py, fastmri/data/subsample.py, fastmri/data/transforms.py, fastmri/data/volume_sampler.py, fastmri/evaluate.py, fastmri/losses.py, fastmri/math.py, fastmri/models/unet.py, fastmri/models/varnet.py, fastmri/pl_modules/data_module.py, fastmri/pl_modules/mri_module.py, fastmri/pl_modules/varnet_module.py, fastmri/utils.py, mypy.ini
This adds type stubs and a `mypy` test to CircleCI.
=> Add typing

experimental/unet/train_unet_demo.py, experimental/varnet/train_varnet_demo.py, fastmri/data/__init__.py, fastmri/data/mri_data.py, fastmri/pl_modules/data_module.py
This adds a few updates for the `CombinedSliceDataset`, adding it to one `__init__.py` and incorporating it into the PTL data module.
=> Combined dataset update

README.md
These badges were mistakenly added to the README.
=> Remove terms and privacy badge

fastmri/data/mri_data.py, fastmri/pl_modules/data_module.py
If `sample_rate < 1.0`, `SliceDataset` subsamples the training dataset by slices and not by volumes. This is undesired since 
1. Based on the function documentation says `sample_rate` should control what fraction of the volumes should be loaded. 
2. Subsampling by volumes makes more sense in practice. Randomly selected slices can create very unbalanced datasets (possibly lots of empty slices) and subsampling by volumes mimics the real life case of having less MRI volumes for training.  
This fix modifies `SliceDataset` to subsample by volumes when `sample_rate < 1.0`. If subsampling by slice is the desired behavior, then we should update the fuction helper to reflect that.
=> Subsample dataset by volume fix

fastmri/pl_modules/data_module.py
When using `ddp` training, workers with the same `id` across different  devices share the same initial random seed for the mask function. This decreases the diversity of random masks during training, since the same mask will be generated on different devices throughout training. This fix generates a unique initial random seed for each worker based on their `id`, device `rank` and dataset (in case of `combine_train_val = True`).
=> mask random seed fix

fastmri_examples/unet/run_pretrained_unet_inference.py
=> Fix output typo

README.md
Updates dataset documentations to clarify main sources of information for knee vs. brain data.
=> Update dataset documentation links

banding_removal/README.md, banding_removal/fastmri/args.py, banding_removal/fastmri/base_trainer.py, banding_removal/fastmri/common/evaluate.py, banding_removal/fastmri/common/subsample.py, banding_removal/fastmri/data/mri_data.py, banding_removal/fastmri/data/transforms.py, banding_removal/fastmri/distributed_mixin.py, banding_removal/fastmri/logging_mixin.py, banding_removal/fastmri/model/var_net.py, banding_removal/fastmri/run.py, banding_removal/fastmri/spawn_dist.py, banding_removal/fastmri/ssim_loss_mixin.py, banding_removal/fastmri/training_loop_mixin.py, banding_removal/fastmri/transforms/kspace.py, banding_removal/fastmri/visualization_mixin.py, banding_removal/scripts/pretrain_dev.py, banding_removal/scripts/train.py, banding_removal/scripts/train_dev.py
- Introduces compatibility with newer versions of dependencies
- Fixes an issue with the offsets in the MRI data resulting in failed runs.
- Brings scripts up to the point where they will reproduce the paper results correctly.
- Adds documentation
=> Banding removal improvements

README.md, fastmri/data/README.md, requirements.txt
Couple fixes for READMEs, including Issue #244.
=> README fixes

README.md
Fixes a code path in the README
=> Fix a code path

fastmri/data/mri_data.py, fastmri/data/volume_sampler.py, fastmri/pl_modules/data_module.py, tests/create_temp_data.py, tests/test_data.py
This should close #256
For the unit test I would like to modify the created temporary data, but don't know whether I can do that.
=> Filter function based on metadata for Datasets

banding_removal/fastmri/data/transforms.py
Fixes #266 by removing the problematic code as it's not currently used.
=> Removed dead code

fastmri_examples/RadiologyJohnson2022/README.md, fastmri_examples/RadiologyJohnson2022/RunInference.py
Creating a folder for the inference script used for the prospective knee study. The script was written by Jure in 2019. It needs to be made available (along with the trained model) for the  2022 publication in Radiology. (full reference TBD)
=> Adding Code for Prospective Knee study

fastmri/data/mri_data.py
Fixes an annotation calculation bug for the y location documented in Issue #309.
=> Fix annotation calculation

.github/workflows/build-and-test.yml, .github/workflows/publish-package.yml, setup.cfg
=> Update Python for CI
